# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_fare', models.FloatField(blank=True, null=True)),
                ('max_fare', models.FloatField(blank=True, null=True)),
                ('base_distance', models.FloatField(blank=True, null=True)),
                ('distance_bucket_size', models.FloatField(blank=True, null=True)),
                ('distance_bucket_fare', models.FloatField(blank=True, null=True)),
                ('time_bucket_size', models.PositiveIntegerField(blank=True, null=True)),
                ('time_bucket_fare', models.PositiveIntegerField(blank=True, null=True)),
                ('flags', models.PositiveIntegerField(blank=True, choices=[(1, 'Premium'), (2, 'Economy')], null=True)),
                ('category_type', models.PositiveIntegerField(blank=True, choices=[(1, 'EV'), (2, 'NON_EV')], null=True)),
                ('dead_mileage_thresholds', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('max_seats_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_allowance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('departure_allowance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
                'permissions': [('category_list', 'Can View Categories List'), ('add_category', 'Can Add A Category'), ('edit_category', 'Can Edit A Category'), ('delete_category', 'Can Delete A Category'), ('view_category', 'Can View Category Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('holiday_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holidays',
                'permissions': [('holidays_list', 'Can View Holidays List'), ('add_holiday', 'Can Add A Holiday'), ('edit_holiday', 'Can Edit A Holiday'), ('delete_holiday', 'Can Delete A Holiday'), ('view_holiday', 'Can View Holiday Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
