# Generated by Django 3.0 on 2023-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercodes',
            name='routes',
            field=models.ManyToManyField(to='routes.Routes'),
        ),
    ]
