from django.contrib.auth.models import Permission
from django.db.models import Q


def GetPermissionsList():
    model_name, model_permssions = [],[]
    model_name.append('Customers')
    model_permssions.append(Permission.objects.filter(content_type__model='user').order_by('id'))
    model_name.append('Captains')
    model_permssions.append(Permission.objects.filter(content_type__model='captain').order_by('id'))
    model_name.append('Plans')
    model_permssions.append(Permission.objects.filter(content_type__model='plans').order_by('id'))
    model_name.append('Companies')
    model_permssions.append(Permission.objects.filter(content_type__model='companies').order_by('id'))
    model_name.append('Bus Types')
    model_permssions.append(Permission.objects.filter(content_type__model='bustypes').order_by('id'))
    model_name.append('Buses')
    model_permssions.append(Permission.objects.filter(content_type__model='buses').order_by('id'))
    model_name.append('Categories')
    model_permssions.append(Permission.objects.filter(content_type__model='category').order_by('id'))
    model_name.append('Holidays')
    model_permssions.append(Permission.objects.filter(content_type__model='holidays').order_by('id'))
    model_name.append('Stations')
    model_permssions.append(Permission.objects.filter(content_type__model='stations').order_by('id'))
    model_name.append('Routes')
    model_permssions.append(Permission.objects.filter(content_type__model='routes').order_by('id'))
    model_name.append('Schedules')
    model_permssions.append(Permission.objects.filter(content_type__model='schedules').order_by('id'))
    model_name.append('Rides')
    model_permssions.append(Permission.objects.filter(content_type__model='rides').order_by('id'))
    model_name.append('Rides Search History')
    model_permssions.append(Permission.objects.filter(content_type__model='userridesearch').order_by('id'))
    model_name.append('Dispatcher')
    model_permssions.append(Permission.objects.filter(content_type__model='dispatcher').order_by('id'))
    model_name.append('Bookings')
    model_permssions.append(Permission.objects.filter(content_type__model='booking').order_by('id'))
    model_name.append('Cancellaton Reasons')
    model_permssions.append(Permission.objects.filter(content_type__model='cancelreason').order_by('id'))
    model_name.append('Review Texts')
    model_permssions.append(Permission.objects.filter(content_type__model='reviewtext').order_by('id'))
    model_name.append('Offers')
    model_permssions.append(Permission.objects.filter(content_type__model='offercodes').order_by('id'))
    model_name.append('Currencies')
    model_permssions.append(Permission.objects.filter(content_type__model='currencies').order_by('id'))
    model_name.append('Countries')
    model_permssions.append(Permission.objects.filter(content_type__model='countries').order_by('id'))
    model_name.append('Cities')
    model_permssions.append(Permission.objects.filter(content_type__model='cities').order_by('id'))
    model_name.append('Districts')
    model_permssions.append(Permission.objects.filter(content_type__model='district').order_by('id'))
    model_name.append('Contact Us')
    model_permssions.append(Permission.objects.filter(content_type__model='contactus').order_by('id'))
    model_name.append('Charging Sites')
    model_permssions.append(Permission.objects.filter(content_type__model='chargingsites').order_by('id'))
    model_name.append('Pages')
    model_permssions.append(Permission.objects.filter(content_type__model='pages').order_by('id'))
    model_name.append('Database Management')
    model_permssions.append(Permission.objects.filter(content_type__model='backup').order_by('id'))
    model_name.append('Login History')
    model_permssions.append(Permission.objects.filter(content_type__model='loginhistory').order_by('id'))
    model_name.append('Email Logs')
    model_permssions.append(Permission.objects.filter(content_type__model='emaillogger').order_by('id'))
    model_name.append('Application Error Logs')
    model_permssions.append(Permission.objects.filter(content_type__model='applicationcrashlogs').order_by('id'))
    return zip(model_name, model_permssions)