# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('charging_points_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charging_sites',
                'permissions': [('charging_sites_list', 'Can View Charging Sites List'), ('add_charging_site', 'Can Add A Charging Site'), ('edit_charging_site', 'Can Edit A Charging Site'), ('delete_charging_site', 'Can Delete A Charging Site'), ('view_charging_site', 'Can View Charging Site Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
