# Generated by Django 3.0 on 2023-02-02 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('allow_manual_dispatch', models.BooleanField(blank=True, default=True, null=True)),
                ('run_current_day', models.BooleanField(blank=True, default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('total_runs', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'dispatcher',
                'permissions': [('dispatcher_list', 'Can View Offers List'), ('add_dispatch', 'Can Add A Dispatch'), ('edit_dispatch', 'Can Edit A Dispatch'), ('delete_dispatch', 'Can Delete A Dispatch'), ('view_dispatch', 'Can View Dispatch Details'), ('activate_deactivate_dispatch', 'Can Activate/Deactivate A Dispatch'), ('dispatch_manual_rides', 'Can Dispatch Manual Rides')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DispatcherReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatched_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('rides_dispatched', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Dispatch Success'), (2, 'Dispatch Failure')], null=True)),
                ('dispatch_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Automatic'), (2, 'Manual')], null=True)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Dispatcher')),
            ],
            options={
                'db_table': 'dispatcher_reports',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
