# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('holidays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherreports',
            name='rides',
            field=models.ManyToManyField(to='routes.Rides'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='categories',
            field=models.ManyToManyField(to='holidays.Category'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='cities',
            field=models.ManyToManyField(to='accounts.Cities'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
