# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionActivityLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_url', models.CharField(blank=True, help_text='API URL', max_length=1024, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('body_data', models.TextField(blank=True, null=True)),
                ('api_method', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Response status code', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('action_type', models.PositiveIntegerField(blank=True, choices=[(1, 'API_Action'), (2, 'Backend_Action')], default=1, help_text='BACKEND OR API', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_activity_logs',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
