# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seat_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('max_seat_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bus_types',
                'permissions': [('bus_type_list', 'Can View Bus Types List'), ('add_bus_type', 'Can Add A Bus Type'), ('edit_bus_type', 'Can Edit A Bus Type'), ('delete_bus_type', 'Can Delete A Bus Type'), ('view_bus_type', 'Can View Bus Type Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_ac', models.BooleanField(default=False)),
                ('is_sacco', models.BooleanField(default=False)),
                ('is_ev', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('manufacture_year', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ownership_start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_regular', models.BooleanField(blank=True, default=True, null=True)),
                ('bus_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.BusTypes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ownership_document', models.ManyToManyField(related_name='ownership_document', to='accounts.Image')),
                ('vehicle_image', models.ManyToManyField(related_name='vehicle_image', to='accounts.Image')),
            ],
            options={
                'db_table': 'buses',
                'permissions': [('bus_list', 'Can View Buses List'), ('add_bus', 'Can Add A Bus'), ('edit_bus', 'Can Edit A Bus'), ('delete_bus', 'Can Delete A Bus'), ('view_bus', 'Can View Bus Details'), ('activate_deactivate_bus', 'Can Activate/Deactivate A Bus')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
