# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPOC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='company_poc')),
            ],
            options={
                'db_table': 'company_poc',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Weekdays'), (2, 'Weekend'), (3, 'Both Weekdays & Weekend')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('shift_type', models.PositiveIntegerField(blank=True, choices=[(1, 'FullTime'), (2, 'PartTime')], null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans',
                'permissions': [('plans_list', 'Can View Plans List'), ('add_plan', 'Can Add A Plan'), ('edit_plan', 'Can Edit A Plan'), ('delete_plan', 'Can Delete A Plan'), ('view_plan', 'Can View Plan Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logo/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('company_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Sacco')], null=True)),
                ('payment_mode', models.PositiveIntegerField(blank=True, choices=[(1, 'Bank Transfer'), (2, 'Mobile Money')], null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_poc', models.ManyToManyField(to='captains.CompanyPOC')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
                'permissions': [('companies_list', 'Can View Companies List'), ('add_company', 'Can Add A Company'), ('edit_company', 'Can Edit A Company'), ('delete_company', 'Can Delete A Company'), ('view_company', 'Can View Company Details')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('garage_location', models.TextField(blank=True, null=True)),
                ('garage_lattitude', models.FloatField(blank=True, null=True)),
                ('garage_longitude', models.FloatField(blank=True, null=True)),
                ('sacco_rsl', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_blacklisted', models.BooleanField(blank=True, default=False, null=True)),
                ('mode_of_payment', models.PositiveIntegerField(blank=True, choices=[(1, 'SACCO'), (2, 'Individual'), (3, 'Supplier')], null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('driving_license_expiry_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain_user', to='captains.Companies')),
                ('driving_license', models.ManyToManyField(related_name='driving_license', to='accounts.Image')),
                ('govt_id_proof', models.ManyToManyField(related_name='govt_id_proof', to='accounts.Image')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captains.Plans')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'captain',
                'permissions': [('captains_list', 'Can View Captains List'), ('add_captain', 'Can Add A Captain'), ('edit_captain', 'Can Edit A Captain Profile'), ('view_captain', 'Can View Captain Details'), ('verify_unverify_captain', 'Can Verify/Unverify Captain Profile'), ('activate_deactivate_delete_captain', 'Can Activate/Deactivate/Delete Captain Profile'), ('assign_company', 'Can Assign Company'), ('assign_plan', 'Can Assign Plan'), ('assign_bus', 'Can Assign Bus')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssignedCaptainBuses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.Buses')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captains.Captain')),
            ],
            options={
                'db_table': 'assigned_captain_buses',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
