# Generated by Django 3.0 on 2023-02-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCrashLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('referer_link', models.TextField(blank=True, null=True)),
                ('user_ip', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'application_crash_logs',
                'permissions': [('application_crashes_list', 'Can View Application Error Logs List'), ('view_application_crash', 'Can View An Application Error Log Details'), ('delete_application_crash', 'Can Delete An Application Error Log'), ('clear_application_crashes', 'Can Clear All Application Error Logs')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmailLogger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('recievers_email', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('reciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_logger',
                'permissions': [('email_logs_list', 'Can View Email Logs List'), ('view_email_log', 'Can View An Email Log Details'), ('delete_email_log', 'Can Delete An Email Log'), ('clear_email_logs', 'Can Clear All Email Logs')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
