# Generated by Django 3.0 on 2023-02-02 16:43

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type_id', models.PositiveIntegerField(choices=[(1, 'Terms_And_Condition'), (2, 'Privacy_Policy'), (3, 'About_Us'), (4, 'Ride Cancellation Policy')])),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'static_pages',
                'permissions': [('pages_list', 'Can View Static Pages List'), ('add_page', 'Can Add A Static Page'), ('edit_page', 'Can Edit A Static Page'), ('view_page', 'Can View Static Page Details'), ('delete_page', 'Can Delete A Static Page')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
